# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sua_title', models.CharField(max_length=200)),
                ('sua_team', models.CharField(max_length=200)),
                ('sua_date', models.DateTimeField(verbose_name='活动日期')),
                ('sua_hours', models.IntegerField()),
            ],
        ),
    ]
