# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('sua', '0002_auto_20170711_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number', models.IntegerField(verbose_name='Student Number')),
                ('suahours', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2017, verbose_name='Student Grade')),
            ],
        ),
        migrations.RenameField(
            model_name='sua',
            old_name='sua_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sua',
            old_name='sua_hours',
            new_name='suahours',
        ),
        migrations.RenameField(
            model_name='sua',
            old_name='sua_team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='sua',
            old_name='sua_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sua',
            name='user',
        ),
        migrations.AddField(
            model_name='sua',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sua',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sua.Student'),
            preserve_default=False,
        ),
    ]
