# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0003_auto_20170711_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sua',
            name='last_time_suahours',
            field=models.FloatField(default=0.0),
        ),
    ]
