# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0004_sua_last_time_suahours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sua',
            name='team',
            field=models.CharField(default='未分组', max_length=200),
        ),
    ]
