# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0005_auto_20170712_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='sua',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
