# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sua', '0006_sua_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='生成日期')),
                ('is_offline', models.BooleanField(default=False)),
                ('proof_filename', models.CharField(max_length=400)),
                ('proof_file', models.FileField(upload_to='proofs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sua_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='申请日期')),
                ('detail', models.CharField(max_length=400)),
                ('contact', models.CharField(max_length=100)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.Proof')),
                ('sua', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sua.Sua')),
            ],
        ),
    ]
