# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import sua.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0007_proof_sua_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='proof_filename',
        ),
        migrations.AlterField(
            model_name='proof',
            name='proof_file',
            field=models.FileField(storage=sua.storage.FileStorage(), upload_to='proofs'),
        ),
    ]
