# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import sua.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0008_auto_20170712_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='proof_file',
            field=models.FileField(blank=True, storage=sua.storage.FileStorage(), upload_to='proofs'),
        ),
    ]
