# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0009_auto_20170712_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sua_application',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
