# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('sua', '0010_sua_application_is_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='sua',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.SuaGroup'),
        ),
    ]
