# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sua', '0012_auto_20170714_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='活动日期')),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GSuaPublicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=400)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_begin_date', models.DateTimeField(verbose_name='开始公示时间')),
                ('published_end_date', models.DateTimeField(verbose_name='结束公示时间')),
                ('gsua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.GSua')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='suagroup',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sua_application',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gsua',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.SuaGroup'),
        ),
        migrations.AddField(
            model_name='gsua',
            name='suas',
            field=models.ManyToManyField(to='sua.Sua'),
        ),
    ]
