# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0013_auto_20170714_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='申诉日期')),
                ('claim', models.CharField(max_length=400)),
                ('reason', models.CharField(max_length=400)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('feedback', models.CharField(max_length=400)),
                ('gsua', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sua.GSua')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.Student')),
                ('sua', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sua.Sua')),
            ],
        ),
    ]
