# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0017_auto_20170715_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='reason',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
