# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0018_auto_20170929_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='suahours',
            field=models.FloatField(default=0),
        ),
    ]
