# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0019_auto_20171013_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suagroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='suagroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group'),
        ),
    ]
