# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0021_suagroup_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsuapublicity',
            name='published_begin_date',
            field=models.DateTimeField(default=2017, verbose_name='开始公示时间'),
        ),
        migrations.AlterField(
            model_name='sua',
            name='team',
            field=models.CharField(max_length=200),
        ),
    ]
