# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0022_auto_20171015_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsuapublicity',
            name='published_begin_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 15, 20, 56, 21, 649855), verbose_name='开始公示时间'),
        ),
    ]
