# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0023_auto_20171015_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsuapublicity',
            name='published_begin_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 22, 22, 51, 149253), verbose_name='开始公示时间'),
        ),
    ]
