# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0023_auto_20171015_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.IntegerField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='gsuapublicity',
            name='published_begin_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 10, 44, 6, 736193), verbose_name='开始公示时间'),
        ),
    ]
