# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0024_auto_20171022_2222'),
        ('sua', '0025_auto_20171101_2355'),
    ]

    operations = [
    ]
