# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sua', '0026_merge_20171214_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsuapublicity',
            name='published_begin_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 21, 2, 33, 850548), verbose_name='开始公示时间'),
        ),
    ]
